/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhosRealizadosRouteImport } from './routes/trabalhos-realizados'
import { Route as SolucoesWebRouteImport } from './routes/solucoes-web'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SistemaSobDemandaNcBrasilRouteImport } from './routes/sistema-sob-demanda-nc-brasil'
import { Route as SistemaDeLeilaoRouteImport } from './routes/sistema-de-leilao'
import { Route as ProgramaDeOrdemDeServicoRouteImport } from './routes/programa-de-ordem-de-servico'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as NossosSistemasRouteImport } from './routes/nossos-sistemas'
import { Route as NossosServicosRouteImport } from './routes/nossos-servicos'
import { Route as InstagramParaEmpresasRouteImport } from './routes/instagram-para-empresas'
import { Route as ErrosNaCriacaoDeUmAplicativoRouteImport } from './routes/erros-na-criacao-de-um-aplicativo'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DicasParaECommerceRouteImport } from './routes/dicas-para-e-commerce'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SistemasIndexRouteImport } from './routes/sistemas.index'
import { Route as SistemasSistemaDeRifasRouteImport } from './routes/sistemas.sistema-de-rifas'
import { Route as SistemasSistemaDeRevendaDeVeiculosRouteImport } from './routes/sistemas.sistema-de-revenda-de-veiculos'
import { Route as SistemasSistemaDeRaspadinhaRouteImport } from './routes/sistemas.sistema-de-raspadinha'
import { Route as SistemasSistemaDeOfertasCupomMarketplaceRouteImport } from './routes/sistemas.sistema-de-ofertas-cupom-marketplace'
import { Route as SistemasSistemaDeLeilaoRuralRouteImport } from './routes/sistemas.sistema-de-leilao-rural'
import { Route as SistemasSistemaDeLeilaoDeCentavosRouteImport } from './routes/sistemas.sistema-de-leilao-de-centavos'
import { Route as SistemasSistemaDeLeilaoRouteImport } from './routes/sistemas.sistema-de-leilao'
import { Route as SistemasSistemaDeCupomDescontosRouteImport } from './routes/sistemas.sistema-de-cupom-descontos'
import { Route as SistemasPlataformaChinesaApostasCassinoRouteImport } from './routes/sistemas.plataforma-chinesa-apostas-cassino'
import { Route as SistemasClassificadosDeVeiculosRouteImport } from './routes/sistemas.classificados-de-veiculos'
import { Route as PortfolioSistemaDeCompraColetivaRouteImport } from './routes/portfolio.sistema-de-compra-coletiva'
import { Route as PortfolioLojasVirtuaisCriadasRouteImport } from './routes/portfolio.lojas-virtuais-criadas'
import { Route as PortfolioLogotiposCriadosRouteImport } from './routes/portfolio.logotipos-criados'
import { Route as PortfolioIdentidadeVisualRouteImport } from './routes/portfolio.identidade-visual'
import { Route as PortfolioCriacaoDeSistemasRouteImport } from './routes/portfolio.criacao-de-sistemas'
import { Route as PortfolioCriacaoDeLogomarcasRouteImport } from './routes/portfolio.criacao-de-logomarcas'
import { Route as PortfolioCriacaoDeAplicativosRouteImport } from './routes/portfolio.criacao-de-aplicativos'

const TrabalhosRealizadosRoute = TrabalhosRealizadosRouteImport.update({
  id: '/trabalhos-realizados',
  path: '/trabalhos-realizados',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesWebRoute = SolucoesWebRouteImport.update({
  id: '/solucoes-web',
  path: '/solucoes-web',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaSobDemandaNcBrasilRoute =
  SistemaSobDemandaNcBrasilRouteImport.update({
    id: '/sistema-sob-demanda-nc-brasil',
    path: '/sistema-sob-demanda-nc-brasil',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemaDeLeilaoRoute = SistemaDeLeilaoRouteImport.update({
  id: '/sistema-de-leilao',
  path: '/sistema-de-leilao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaDeOrdemDeServicoRoute =
  ProgramaDeOrdemDeServicoRouteImport.update({
    id: '/programa-de-ordem-de-servico',
    path: '/programa-de-ordem-de-servico',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const NossosSistemasRoute = NossosSistemasRouteImport.update({
  id: '/nossos-sistemas',
  path: '/nossos-sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const NossosServicosRoute = NossosServicosRouteImport.update({
  id: '/nossos-servicos',
  path: '/nossos-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramParaEmpresasRoute = InstagramParaEmpresasRouteImport.update({
  id: '/instagram-para-empresas',
  path: '/instagram-para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosNaCriacaoDeUmAplicativoRoute =
  ErrosNaCriacaoDeUmAplicativoRouteImport.update({
    id: '/erros-na-criacao-de-um-aplicativo',
    path: '/erros-na-criacao-de-um-aplicativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasParaECommerceRoute = DicasParaECommerceRouteImport.update({
  id: '/dicas-para-e-commerce',
  path: '/dicas-para-e-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasIndexRoute = SistemasIndexRouteImport.update({
  id: '/sistemas/',
  path: '/sistemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasSistemaDeRifasRoute = SistemasSistemaDeRifasRouteImport.update({
  id: '/sistemas/sistema-de-rifas',
  path: '/sistemas/sistema-de-rifas',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasSistemaDeRevendaDeVeiculosRoute =
  SistemasSistemaDeRevendaDeVeiculosRouteImport.update({
    id: '/sistemas/sistema-de-revenda-de-veiculos',
    path: '/sistemas/sistema-de-revenda-de-veiculos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasSistemaDeRaspadinhaRoute =
  SistemasSistemaDeRaspadinhaRouteImport.update({
    id: '/sistemas/sistema-de-raspadinha',
    path: '/sistemas/sistema-de-raspadinha',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasSistemaDeOfertasCupomMarketplaceRoute =
  SistemasSistemaDeOfertasCupomMarketplaceRouteImport.update({
    id: '/sistemas/sistema-de-ofertas-cupom-marketplace',
    path: '/sistemas/sistema-de-ofertas-cupom-marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasSistemaDeLeilaoRuralRoute =
  SistemasSistemaDeLeilaoRuralRouteImport.update({
    id: '/sistemas/sistema-de-leilao-rural',
    path: '/sistemas/sistema-de-leilao-rural',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasSistemaDeLeilaoDeCentavosRoute =
  SistemasSistemaDeLeilaoDeCentavosRouteImport.update({
    id: '/sistemas/sistema-de-leilao-de-centavos',
    path: '/sistemas/sistema-de-leilao-de-centavos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasSistemaDeLeilaoRoute = SistemasSistemaDeLeilaoRouteImport.update({
  id: '/sistemas/sistema-de-leilao',
  path: '/sistemas/sistema-de-leilao',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasSistemaDeCupomDescontosRoute =
  SistemasSistemaDeCupomDescontosRouteImport.update({
    id: '/sistemas/sistema-de-cupom-descontos',
    path: '/sistemas/sistema-de-cupom-descontos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasPlataformaChinesaApostasCassinoRoute =
  SistemasPlataformaChinesaApostasCassinoRouteImport.update({
    id: '/sistemas/plataforma-chinesa-apostas-cassino',
    path: '/sistemas/plataforma-chinesa-apostas-cassino',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemasClassificadosDeVeiculosRoute =
  SistemasClassificadosDeVeiculosRouteImport.update({
    id: '/sistemas/classificados-de-veiculos',
    path: '/sistemas/classificados-de-veiculos',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioSistemaDeCompraColetivaRoute =
  PortfolioSistemaDeCompraColetivaRouteImport.update({
    id: '/portfolio/sistema-de-compra-coletiva',
    path: '/portfolio/sistema-de-compra-coletiva',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioLojasVirtuaisCriadasRoute =
  PortfolioLojasVirtuaisCriadasRouteImport.update({
    id: '/portfolio/lojas-virtuais-criadas',
    path: '/portfolio/lojas-virtuais-criadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioLogotiposCriadosRoute =
  PortfolioLogotiposCriadosRouteImport.update({
    id: '/portfolio/logotipos-criados',
    path: '/portfolio/logotipos-criados',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioIdentidadeVisualRoute =
  PortfolioIdentidadeVisualRouteImport.update({
    id: '/portfolio/identidade-visual',
    path: '/portfolio/identidade-visual',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCriacaoDeSistemasRoute =
  PortfolioCriacaoDeSistemasRouteImport.update({
    id: '/portfolio/criacao-de-sistemas',
    path: '/portfolio/criacao-de-sistemas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCriacaoDeLogomarcasRoute =
  PortfolioCriacaoDeLogomarcasRouteImport.update({
    id: '/portfolio/criacao-de-logomarcas',
    path: '/portfolio/criacao-de-logomarcas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCriacaoDeAplicativosRoute =
  PortfolioCriacaoDeAplicativosRouteImport.update({
    id: '/portfolio/criacao-de-aplicativos',
    path: '/portfolio/criacao-de-aplicativos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/dicas-para-e-commerce': typeof DicasParaECommerceRoute
  '/empresa': typeof EmpresaRoute
  '/erros-na-criacao-de-um-aplicativo': typeof ErrosNaCriacaoDeUmAplicativoRoute
  '/instagram-para-empresas': typeof InstagramParaEmpresasRoute
  '/nossos-servicos': typeof NossosServicosRoute
  '/nossos-sistemas': typeof NossosSistemasRoute
  '/orcamento': typeof OrcamentoRoute
  '/programa-de-ordem-de-servico': typeof ProgramaDeOrdemDeServicoRoute
  '/sistema-de-leilao': typeof SistemaDeLeilaoRoute
  '/sistema-sob-demanda-nc-brasil': typeof SistemaSobDemandaNcBrasilRoute
  '/software': typeof SoftwareRoute
  '/solucoes-web': typeof SolucoesWebRoute
  '/trabalhos-realizados': typeof TrabalhosRealizadosRoute
  '/portfolio/criacao-de-aplicativos': typeof PortfolioCriacaoDeAplicativosRoute
  '/portfolio/criacao-de-logomarcas': typeof PortfolioCriacaoDeLogomarcasRoute
  '/portfolio/criacao-de-sistemas': typeof PortfolioCriacaoDeSistemasRoute
  '/portfolio/identidade-visual': typeof PortfolioIdentidadeVisualRoute
  '/portfolio/logotipos-criados': typeof PortfolioLogotiposCriadosRoute
  '/portfolio/lojas-virtuais-criadas': typeof PortfolioLojasVirtuaisCriadasRoute
  '/portfolio/sistema-de-compra-coletiva': typeof PortfolioSistemaDeCompraColetivaRoute
  '/sistemas/classificados-de-veiculos': typeof SistemasClassificadosDeVeiculosRoute
  '/sistemas/plataforma-chinesa-apostas-cassino': typeof SistemasPlataformaChinesaApostasCassinoRoute
  '/sistemas/sistema-de-cupom-descontos': typeof SistemasSistemaDeCupomDescontosRoute
  '/sistemas/sistema-de-leilao': typeof SistemasSistemaDeLeilaoRoute
  '/sistemas/sistema-de-leilao-de-centavos': typeof SistemasSistemaDeLeilaoDeCentavosRoute
  '/sistemas/sistema-de-leilao-rural': typeof SistemasSistemaDeLeilaoRuralRoute
  '/sistemas/sistema-de-ofertas-cupom-marketplace': typeof SistemasSistemaDeOfertasCupomMarketplaceRoute
  '/sistemas/sistema-de-raspadinha': typeof SistemasSistemaDeRaspadinhaRoute
  '/sistemas/sistema-de-revenda-de-veiculos': typeof SistemasSistemaDeRevendaDeVeiculosRoute
  '/sistemas/sistema-de-rifas': typeof SistemasSistemaDeRifasRoute
  '/sistemas/': typeof SistemasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/dicas-para-e-commerce': typeof DicasParaECommerceRoute
  '/empresa': typeof EmpresaRoute
  '/erros-na-criacao-de-um-aplicativo': typeof ErrosNaCriacaoDeUmAplicativoRoute
  '/instagram-para-empresas': typeof InstagramParaEmpresasRoute
  '/nossos-servicos': typeof NossosServicosRoute
  '/nossos-sistemas': typeof NossosSistemasRoute
  '/orcamento': typeof OrcamentoRoute
  '/programa-de-ordem-de-servico': typeof ProgramaDeOrdemDeServicoRoute
  '/sistema-de-leilao': typeof SistemaDeLeilaoRoute
  '/sistema-sob-demanda-nc-brasil': typeof SistemaSobDemandaNcBrasilRoute
  '/software': typeof SoftwareRoute
  '/solucoes-web': typeof SolucoesWebRoute
  '/trabalhos-realizados': typeof TrabalhosRealizadosRoute
  '/portfolio/criacao-de-aplicativos': typeof PortfolioCriacaoDeAplicativosRoute
  '/portfolio/criacao-de-logomarcas': typeof PortfolioCriacaoDeLogomarcasRoute
  '/portfolio/criacao-de-sistemas': typeof PortfolioCriacaoDeSistemasRoute
  '/portfolio/identidade-visual': typeof PortfolioIdentidadeVisualRoute
  '/portfolio/logotipos-criados': typeof PortfolioLogotiposCriadosRoute
  '/portfolio/lojas-virtuais-criadas': typeof PortfolioLojasVirtuaisCriadasRoute
  '/portfolio/sistema-de-compra-coletiva': typeof PortfolioSistemaDeCompraColetivaRoute
  '/sistemas/classificados-de-veiculos': typeof SistemasClassificadosDeVeiculosRoute
  '/sistemas/plataforma-chinesa-apostas-cassino': typeof SistemasPlataformaChinesaApostasCassinoRoute
  '/sistemas/sistema-de-cupom-descontos': typeof SistemasSistemaDeCupomDescontosRoute
  '/sistemas/sistema-de-leilao': typeof SistemasSistemaDeLeilaoRoute
  '/sistemas/sistema-de-leilao-de-centavos': typeof SistemasSistemaDeLeilaoDeCentavosRoute
  '/sistemas/sistema-de-leilao-rural': typeof SistemasSistemaDeLeilaoRuralRoute
  '/sistemas/sistema-de-ofertas-cupom-marketplace': typeof SistemasSistemaDeOfertasCupomMarketplaceRoute
  '/sistemas/sistema-de-raspadinha': typeof SistemasSistemaDeRaspadinhaRoute
  '/sistemas/sistema-de-revenda-de-veiculos': typeof SistemasSistemaDeRevendaDeVeiculosRoute
  '/sistemas/sistema-de-rifas': typeof SistemasSistemaDeRifasRoute
  '/sistemas': typeof SistemasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/dicas-para-e-commerce': typeof DicasParaECommerceRoute
  '/empresa': typeof EmpresaRoute
  '/erros-na-criacao-de-um-aplicativo': typeof ErrosNaCriacaoDeUmAplicativoRoute
  '/instagram-para-empresas': typeof InstagramParaEmpresasRoute
  '/nossos-servicos': typeof NossosServicosRoute
  '/nossos-sistemas': typeof NossosSistemasRoute
  '/orcamento': typeof OrcamentoRoute
  '/programa-de-ordem-de-servico': typeof ProgramaDeOrdemDeServicoRoute
  '/sistema-de-leilao': typeof SistemaDeLeilaoRoute
  '/sistema-sob-demanda-nc-brasil': typeof SistemaSobDemandaNcBrasilRoute
  '/software': typeof SoftwareRoute
  '/solucoes-web': typeof SolucoesWebRoute
  '/trabalhos-realizados': typeof TrabalhosRealizadosRoute
  '/portfolio/criacao-de-aplicativos': typeof PortfolioCriacaoDeAplicativosRoute
  '/portfolio/criacao-de-logomarcas': typeof PortfolioCriacaoDeLogomarcasRoute
  '/portfolio/criacao-de-sistemas': typeof PortfolioCriacaoDeSistemasRoute
  '/portfolio/identidade-visual': typeof PortfolioIdentidadeVisualRoute
  '/portfolio/logotipos-criados': typeof PortfolioLogotiposCriadosRoute
  '/portfolio/lojas-virtuais-criadas': typeof PortfolioLojasVirtuaisCriadasRoute
  '/portfolio/sistema-de-compra-coletiva': typeof PortfolioSistemaDeCompraColetivaRoute
  '/sistemas/classificados-de-veiculos': typeof SistemasClassificadosDeVeiculosRoute
  '/sistemas/plataforma-chinesa-apostas-cassino': typeof SistemasPlataformaChinesaApostasCassinoRoute
  '/sistemas/sistema-de-cupom-descontos': typeof SistemasSistemaDeCupomDescontosRoute
  '/sistemas/sistema-de-leilao': typeof SistemasSistemaDeLeilaoRoute
  '/sistemas/sistema-de-leilao-de-centavos': typeof SistemasSistemaDeLeilaoDeCentavosRoute
  '/sistemas/sistema-de-leilao-rural': typeof SistemasSistemaDeLeilaoRuralRoute
  '/sistemas/sistema-de-ofertas-cupom-marketplace': typeof SistemasSistemaDeOfertasCupomMarketplaceRoute
  '/sistemas/sistema-de-raspadinha': typeof SistemasSistemaDeRaspadinhaRoute
  '/sistemas/sistema-de-revenda-de-veiculos': typeof SistemasSistemaDeRevendaDeVeiculosRoute
  '/sistemas/sistema-de-rifas': typeof SistemasSistemaDeRifasRoute
  '/sistemas/': typeof SistemasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/dicas-para-e-commerce'
    | '/empresa'
    | '/erros-na-criacao-de-um-aplicativo'
    | '/instagram-para-empresas'
    | '/nossos-servicos'
    | '/nossos-sistemas'
    | '/orcamento'
    | '/programa-de-ordem-de-servico'
    | '/sistema-de-leilao'
    | '/sistema-sob-demanda-nc-brasil'
    | '/software'
    | '/solucoes-web'
    | '/trabalhos-realizados'
    | '/portfolio/criacao-de-aplicativos'
    | '/portfolio/criacao-de-logomarcas'
    | '/portfolio/criacao-de-sistemas'
    | '/portfolio/identidade-visual'
    | '/portfolio/logotipos-criados'
    | '/portfolio/lojas-virtuais-criadas'
    | '/portfolio/sistema-de-compra-coletiva'
    | '/sistemas/classificados-de-veiculos'
    | '/sistemas/plataforma-chinesa-apostas-cassino'
    | '/sistemas/sistema-de-cupom-descontos'
    | '/sistemas/sistema-de-leilao'
    | '/sistemas/sistema-de-leilao-de-centavos'
    | '/sistemas/sistema-de-leilao-rural'
    | '/sistemas/sistema-de-ofertas-cupom-marketplace'
    | '/sistemas/sistema-de-raspadinha'
    | '/sistemas/sistema-de-revenda-de-veiculos'
    | '/sistemas/sistema-de-rifas'
    | '/sistemas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/dicas-para-e-commerce'
    | '/empresa'
    | '/erros-na-criacao-de-um-aplicativo'
    | '/instagram-para-empresas'
    | '/nossos-servicos'
    | '/nossos-sistemas'
    | '/orcamento'
    | '/programa-de-ordem-de-servico'
    | '/sistema-de-leilao'
    | '/sistema-sob-demanda-nc-brasil'
    | '/software'
    | '/solucoes-web'
    | '/trabalhos-realizados'
    | '/portfolio/criacao-de-aplicativos'
    | '/portfolio/criacao-de-logomarcas'
    | '/portfolio/criacao-de-sistemas'
    | '/portfolio/identidade-visual'
    | '/portfolio/logotipos-criados'
    | '/portfolio/lojas-virtuais-criadas'
    | '/portfolio/sistema-de-compra-coletiva'
    | '/sistemas/classificados-de-veiculos'
    | '/sistemas/plataforma-chinesa-apostas-cassino'
    | '/sistemas/sistema-de-cupom-descontos'
    | '/sistemas/sistema-de-leilao'
    | '/sistemas/sistema-de-leilao-de-centavos'
    | '/sistemas/sistema-de-leilao-rural'
    | '/sistemas/sistema-de-ofertas-cupom-marketplace'
    | '/sistemas/sistema-de-raspadinha'
    | '/sistemas/sistema-de-revenda-de-veiculos'
    | '/sistemas/sistema-de-rifas'
    | '/sistemas'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/dicas-para-e-commerce'
    | '/empresa'
    | '/erros-na-criacao-de-um-aplicativo'
    | '/instagram-para-empresas'
    | '/nossos-servicos'
    | '/nossos-sistemas'
    | '/orcamento'
    | '/programa-de-ordem-de-servico'
    | '/sistema-de-leilao'
    | '/sistema-sob-demanda-nc-brasil'
    | '/software'
    | '/solucoes-web'
    | '/trabalhos-realizados'
    | '/portfolio/criacao-de-aplicativos'
    | '/portfolio/criacao-de-logomarcas'
    | '/portfolio/criacao-de-sistemas'
    | '/portfolio/identidade-visual'
    | '/portfolio/logotipos-criados'
    | '/portfolio/lojas-virtuais-criadas'
    | '/portfolio/sistema-de-compra-coletiva'
    | '/sistemas/classificados-de-veiculos'
    | '/sistemas/plataforma-chinesa-apostas-cassino'
    | '/sistemas/sistema-de-cupom-descontos'
    | '/sistemas/sistema-de-leilao'
    | '/sistemas/sistema-de-leilao-de-centavos'
    | '/sistemas/sistema-de-leilao-rural'
    | '/sistemas/sistema-de-ofertas-cupom-marketplace'
    | '/sistemas/sistema-de-raspadinha'
    | '/sistemas/sistema-de-revenda-de-veiculos'
    | '/sistemas/sistema-de-rifas'
    | '/sistemas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DicasParaECommerceRoute: typeof DicasParaECommerceRoute
  EmpresaRoute: typeof EmpresaRoute
  ErrosNaCriacaoDeUmAplicativoRoute: typeof ErrosNaCriacaoDeUmAplicativoRoute
  InstagramParaEmpresasRoute: typeof InstagramParaEmpresasRoute
  NossosServicosRoute: typeof NossosServicosRoute
  NossosSistemasRoute: typeof NossosSistemasRoute
  OrcamentoRoute: typeof OrcamentoRoute
  ProgramaDeOrdemDeServicoRoute: typeof ProgramaDeOrdemDeServicoRoute
  SistemaDeLeilaoRoute: typeof SistemaDeLeilaoRoute
  SistemaSobDemandaNcBrasilRoute: typeof SistemaSobDemandaNcBrasilRoute
  SoftwareRoute: typeof SoftwareRoute
  SolucoesWebRoute: typeof SolucoesWebRoute
  TrabalhosRealizadosRoute: typeof TrabalhosRealizadosRoute
  PortfolioCriacaoDeAplicativosRoute: typeof PortfolioCriacaoDeAplicativosRoute
  PortfolioCriacaoDeLogomarcasRoute: typeof PortfolioCriacaoDeLogomarcasRoute
  PortfolioCriacaoDeSistemasRoute: typeof PortfolioCriacaoDeSistemasRoute
  PortfolioIdentidadeVisualRoute: typeof PortfolioIdentidadeVisualRoute
  PortfolioLogotiposCriadosRoute: typeof PortfolioLogotiposCriadosRoute
  PortfolioLojasVirtuaisCriadasRoute: typeof PortfolioLojasVirtuaisCriadasRoute
  PortfolioSistemaDeCompraColetivaRoute: typeof PortfolioSistemaDeCompraColetivaRoute
  SistemasClassificadosDeVeiculosRoute: typeof SistemasClassificadosDeVeiculosRoute
  SistemasPlataformaChinesaApostasCassinoRoute: typeof SistemasPlataformaChinesaApostasCassinoRoute
  SistemasSistemaDeCupomDescontosRoute: typeof SistemasSistemaDeCupomDescontosRoute
  SistemasSistemaDeLeilaoRoute: typeof SistemasSistemaDeLeilaoRoute
  SistemasSistemaDeLeilaoDeCentavosRoute: typeof SistemasSistemaDeLeilaoDeCentavosRoute
  SistemasSistemaDeLeilaoRuralRoute: typeof SistemasSistemaDeLeilaoRuralRoute
  SistemasSistemaDeOfertasCupomMarketplaceRoute: typeof SistemasSistemaDeOfertasCupomMarketplaceRoute
  SistemasSistemaDeRaspadinhaRoute: typeof SistemasSistemaDeRaspadinhaRoute
  SistemasSistemaDeRevendaDeVeiculosRoute: typeof SistemasSistemaDeRevendaDeVeiculosRoute
  SistemasSistemaDeRifasRoute: typeof SistemasSistemaDeRifasRoute
  SistemasIndexRoute: typeof SistemasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhos-realizados': {
      id: '/trabalhos-realizados'
      path: '/trabalhos-realizados'
      fullPath: '/trabalhos-realizados'
      preLoaderRoute: typeof TrabalhosRealizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes-web': {
      id: '/solucoes-web'
      path: '/solucoes-web'
      fullPath: '/solucoes-web'
      preLoaderRoute: typeof SolucoesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-sob-demanda-nc-brasil': {
      id: '/sistema-sob-demanda-nc-brasil'
      path: '/sistema-sob-demanda-nc-brasil'
      fullPath: '/sistema-sob-demanda-nc-brasil'
      preLoaderRoute: typeof SistemaSobDemandaNcBrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-leilao': {
      id: '/sistema-de-leilao'
      path: '/sistema-de-leilao'
      fullPath: '/sistema-de-leilao'
      preLoaderRoute: typeof SistemaDeLeilaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-ordem-de-servico': {
      id: '/programa-de-ordem-de-servico'
      path: '/programa-de-ordem-de-servico'
      fullPath: '/programa-de-ordem-de-servico'
      preLoaderRoute: typeof ProgramaDeOrdemDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossos-sistemas': {
      id: '/nossos-sistemas'
      path: '/nossos-sistemas'
      fullPath: '/nossos-sistemas'
      preLoaderRoute: typeof NossosSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossos-servicos': {
      id: '/nossos-servicos'
      path: '/nossos-servicos'
      fullPath: '/nossos-servicos'
      preLoaderRoute: typeof NossosServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-para-empresas': {
      id: '/instagram-para-empresas'
      path: '/instagram-para-empresas'
      fullPath: '/instagram-para-empresas'
      preLoaderRoute: typeof InstagramParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros-na-criacao-de-um-aplicativo': {
      id: '/erros-na-criacao-de-um-aplicativo'
      path: '/erros-na-criacao-de-um-aplicativo'
      fullPath: '/erros-na-criacao-de-um-aplicativo'
      preLoaderRoute: typeof ErrosNaCriacaoDeUmAplicativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas-para-e-commerce': {
      id: '/dicas-para-e-commerce'
      path: '/dicas-para-e-commerce'
      fullPath: '/dicas-para-e-commerce'
      preLoaderRoute: typeof DicasParaECommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/': {
      id: '/sistemas/'
      path: '/sistemas'
      fullPath: '/sistemas/'
      preLoaderRoute: typeof SistemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-rifas': {
      id: '/sistemas/sistema-de-rifas'
      path: '/sistemas/sistema-de-rifas'
      fullPath: '/sistemas/sistema-de-rifas'
      preLoaderRoute: typeof SistemasSistemaDeRifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-revenda-de-veiculos': {
      id: '/sistemas/sistema-de-revenda-de-veiculos'
      path: '/sistemas/sistema-de-revenda-de-veiculos'
      fullPath: '/sistemas/sistema-de-revenda-de-veiculos'
      preLoaderRoute: typeof SistemasSistemaDeRevendaDeVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-raspadinha': {
      id: '/sistemas/sistema-de-raspadinha'
      path: '/sistemas/sistema-de-raspadinha'
      fullPath: '/sistemas/sistema-de-raspadinha'
      preLoaderRoute: typeof SistemasSistemaDeRaspadinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-ofertas-cupom-marketplace': {
      id: '/sistemas/sistema-de-ofertas-cupom-marketplace'
      path: '/sistemas/sistema-de-ofertas-cupom-marketplace'
      fullPath: '/sistemas/sistema-de-ofertas-cupom-marketplace'
      preLoaderRoute: typeof SistemasSistemaDeOfertasCupomMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-leilao-rural': {
      id: '/sistemas/sistema-de-leilao-rural'
      path: '/sistemas/sistema-de-leilao-rural'
      fullPath: '/sistemas/sistema-de-leilao-rural'
      preLoaderRoute: typeof SistemasSistemaDeLeilaoRuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-leilao-de-centavos': {
      id: '/sistemas/sistema-de-leilao-de-centavos'
      path: '/sistemas/sistema-de-leilao-de-centavos'
      fullPath: '/sistemas/sistema-de-leilao-de-centavos'
      preLoaderRoute: typeof SistemasSistemaDeLeilaoDeCentavosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-leilao': {
      id: '/sistemas/sistema-de-leilao'
      path: '/sistemas/sistema-de-leilao'
      fullPath: '/sistemas/sistema-de-leilao'
      preLoaderRoute: typeof SistemasSistemaDeLeilaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/sistema-de-cupom-descontos': {
      id: '/sistemas/sistema-de-cupom-descontos'
      path: '/sistemas/sistema-de-cupom-descontos'
      fullPath: '/sistemas/sistema-de-cupom-descontos'
      preLoaderRoute: typeof SistemasSistemaDeCupomDescontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/plataforma-chinesa-apostas-cassino': {
      id: '/sistemas/plataforma-chinesa-apostas-cassino'
      path: '/sistemas/plataforma-chinesa-apostas-cassino'
      fullPath: '/sistemas/plataforma-chinesa-apostas-cassino'
      preLoaderRoute: typeof SistemasPlataformaChinesaApostasCassinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/classificados-de-veiculos': {
      id: '/sistemas/classificados-de-veiculos'
      path: '/sistemas/classificados-de-veiculos'
      fullPath: '/sistemas/classificados-de-veiculos'
      preLoaderRoute: typeof SistemasClassificadosDeVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/sistema-de-compra-coletiva': {
      id: '/portfolio/sistema-de-compra-coletiva'
      path: '/portfolio/sistema-de-compra-coletiva'
      fullPath: '/portfolio/sistema-de-compra-coletiva'
      preLoaderRoute: typeof PortfolioSistemaDeCompraColetivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/lojas-virtuais-criadas': {
      id: '/portfolio/lojas-virtuais-criadas'
      path: '/portfolio/lojas-virtuais-criadas'
      fullPath: '/portfolio/lojas-virtuais-criadas'
      preLoaderRoute: typeof PortfolioLojasVirtuaisCriadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/logotipos-criados': {
      id: '/portfolio/logotipos-criados'
      path: '/portfolio/logotipos-criados'
      fullPath: '/portfolio/logotipos-criados'
      preLoaderRoute: typeof PortfolioLogotiposCriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/identidade-visual': {
      id: '/portfolio/identidade-visual'
      path: '/portfolio/identidade-visual'
      fullPath: '/portfolio/identidade-visual'
      preLoaderRoute: typeof PortfolioIdentidadeVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/criacao-de-sistemas': {
      id: '/portfolio/criacao-de-sistemas'
      path: '/portfolio/criacao-de-sistemas'
      fullPath: '/portfolio/criacao-de-sistemas'
      preLoaderRoute: typeof PortfolioCriacaoDeSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/criacao-de-logomarcas': {
      id: '/portfolio/criacao-de-logomarcas'
      path: '/portfolio/criacao-de-logomarcas'
      fullPath: '/portfolio/criacao-de-logomarcas'
      preLoaderRoute: typeof PortfolioCriacaoDeLogomarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/criacao-de-aplicativos': {
      id: '/portfolio/criacao-de-aplicativos'
      path: '/portfolio/criacao-de-aplicativos'
      fullPath: '/portfolio/criacao-de-aplicativos'
      preLoaderRoute: typeof PortfolioCriacaoDeAplicativosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DicasParaECommerceRoute: DicasParaECommerceRoute,
  EmpresaRoute: EmpresaRoute,
  ErrosNaCriacaoDeUmAplicativoRoute: ErrosNaCriacaoDeUmAplicativoRoute,
  InstagramParaEmpresasRoute: InstagramParaEmpresasRoute,
  NossosServicosRoute: NossosServicosRoute,
  NossosSistemasRoute: NossosSistemasRoute,
  OrcamentoRoute: OrcamentoRoute,
  ProgramaDeOrdemDeServicoRoute: ProgramaDeOrdemDeServicoRoute,
  SistemaDeLeilaoRoute: SistemaDeLeilaoRoute,
  SistemaSobDemandaNcBrasilRoute: SistemaSobDemandaNcBrasilRoute,
  SoftwareRoute: SoftwareRoute,
  SolucoesWebRoute: SolucoesWebRoute,
  TrabalhosRealizadosRoute: TrabalhosRealizadosRoute,
  PortfolioCriacaoDeAplicativosRoute: PortfolioCriacaoDeAplicativosRoute,
  PortfolioCriacaoDeLogomarcasRoute: PortfolioCriacaoDeLogomarcasRoute,
  PortfolioCriacaoDeSistemasRoute: PortfolioCriacaoDeSistemasRoute,
  PortfolioIdentidadeVisualRoute: PortfolioIdentidadeVisualRoute,
  PortfolioLogotiposCriadosRoute: PortfolioLogotiposCriadosRoute,
  PortfolioLojasVirtuaisCriadasRoute: PortfolioLojasVirtuaisCriadasRoute,
  PortfolioSistemaDeCompraColetivaRoute: PortfolioSistemaDeCompraColetivaRoute,
  SistemasClassificadosDeVeiculosRoute: SistemasClassificadosDeVeiculosRoute,
  SistemasPlataformaChinesaApostasCassinoRoute:
    SistemasPlataformaChinesaApostasCassinoRoute,
  SistemasSistemaDeCupomDescontosRoute: SistemasSistemaDeCupomDescontosRoute,
  SistemasSistemaDeLeilaoRoute: SistemasSistemaDeLeilaoRoute,
  SistemasSistemaDeLeilaoDeCentavosRoute:
    SistemasSistemaDeLeilaoDeCentavosRoute,
  SistemasSistemaDeLeilaoRuralRoute: SistemasSistemaDeLeilaoRuralRoute,
  SistemasSistemaDeOfertasCupomMarketplaceRoute:
    SistemasSistemaDeOfertasCupomMarketplaceRoute,
  SistemasSistemaDeRaspadinhaRoute: SistemasSistemaDeRaspadinhaRoute,
  SistemasSistemaDeRevendaDeVeiculosRoute:
    SistemasSistemaDeRevendaDeVeiculosRoute,
  SistemasSistemaDeRifasRoute: SistemasSistemaDeRifasRoute,
  SistemasIndexRoute: SistemasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
