/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhosRealizadosRouteImport } from './routes/trabalhos-realizados'
import { Route as SolucoesWebRouteImport } from './routes/solucoes-web'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SistemaSobDemandaNcBrasilRouteImport } from './routes/sistema-sob-demanda-nc-brasil'
import { Route as SistemaDeRifasRouteImport } from './routes/sistema-de-rifas'
import { Route as SistemaDeRevendaDeVeiculosRouteImport } from './routes/sistema-de-revenda-de-veiculos'
import { Route as SistemaDeRaspadinhaRouteImport } from './routes/sistema-de-raspadinha'
import { Route as SistemaDeOfertasCupomMarketplaceRouteImport } from './routes/sistema-de-ofertas-cupom-marketplace'
import { Route as SistemaDeLeilaoRuralRouteImport } from './routes/sistema-de-leilao-rural'
import { Route as SistemaDeLeilaoDeCentavosRouteImport } from './routes/sistema-de-leilao-de-centavos'
import { Route as SistemaDeLeilaoRouteImport } from './routes/sistema-de-leilao'
import { Route as SistemaDeCupomDescontosRouteImport } from './routes/sistema-de-cupom-descontos'
import { Route as ProgramaDeOrdemDeServicoRouteImport } from './routes/programa-de-ordem-de-servico'
import { Route as PlataformaChinesaApostasCassinoRouteImport } from './routes/plataforma-chinesa-apostas-cassino'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as NossosSistemasRouteImport } from './routes/nossos-sistemas'
import { Route as NossosServicosRouteImport } from './routes/nossos-servicos'
import { Route as InstagramParaEmpresasRouteImport } from './routes/instagram-para-empresas'
import { Route as ErrosNaCriacaoDeUmAplicativoRouteImport } from './routes/erros-na-criacao-de-um-aplicativo'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DicasParaECommerceRouteImport } from './routes/dicas-para-e-commerce'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClassificadosDeVeiculosRouteImport } from './routes/classificados-de-veiculos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SistemasIndexRouteImport } from './routes/sistemas.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SolucoesWebSeoGoogleRouteImport } from './routes/solucoes-web.seo-google'
import { Route as SolucoesWebMarketingDigitalRouteImport } from './routes/solucoes-web.marketing-digital'
import { Route as SolucoesWebLojaVirtualRouteImport } from './routes/solucoes-web.loja-virtual'
import { Route as SolucoesWebLandingPagesRouteImport } from './routes/solucoes-web.landing-pages'
import { Route as SolucoesWebHospedagemRouteImport } from './routes/solucoes-web.hospedagem'
import { Route as SolucoesWebDesenvolvimentoDeSitesRouteImport } from './routes/solucoes-web.desenvolvimento-de-sites'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as SistemasSlugRouteImport } from './routes/sistemas.$slug'
import { Route as ServicosSistemasWebRouteImport } from './routes/servicos.sistemas-web'
import { Route as ServicosIdentidadeVisualRouteImport } from './routes/servicos.identidade-visual'
import { Route as ServicosGoogleAdsRouteImport } from './routes/servicos.google-ads'
import { Route as ServicosFacebookAdsRouteImport } from './routes/servicos.facebook-ads'
import { Route as ServicosDesenvolvimentoRouteImport } from './routes/servicos.desenvolvimento'
import { Route as ServicosConsultoriaRouteImport } from './routes/servicos.consultoria'
import { Route as ServicosAplicativosRouteImport } from './routes/servicos.aplicativos'
import { Route as PortfolioSitesCriadosRouteImport } from './routes/portfolio.sites-criados'
import { Route as PortfolioSistemasCriadosRouteImport } from './routes/portfolio.sistemas-criados'
import { Route as PortfolioSistemaDeCompraColetivaRouteImport } from './routes/portfolio.sistema-de-compra-coletiva'
import { Route as PortfolioLojasVirtuaisCriadasRouteImport } from './routes/portfolio.lojas-virtuais-criadas'
import { Route as PortfolioLogotiposCriadosRouteImport } from './routes/portfolio.logotipos-criados'
import { Route as PortfolioIdentidadeVisualRouteImport } from './routes/portfolio.identidade-visual'
import { Route as PortfolioCriacaoDeSistemasRouteImport } from './routes/portfolio.criacao-de-sistemas'
import { Route as PortfolioCriacaoDeLogomarcasRouteImport } from './routes/portfolio.criacao-de-logomarcas'
import { Route as PortfolioCriacaoDeAplicativosRouteImport } from './routes/portfolio.criacao-de-aplicativos'
import { Route as PortfolioAplicativosCriadosRouteImport } from './routes/portfolio.aplicativos-criados'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as EmpresaQuemSomosRouteImport } from './routes/empresa.quem-somos'
import { Route as EmpresaNossaHistoriaRouteImport } from './routes/empresa.nossa-historia'
import { Route as EmpresaClientesRouteImport } from './routes/empresa.clientes'
import { Route as AdminNoticiasRouteImport } from './routes/admin.noticias'
import { Route as AdminImportarRouteImport } from './routes/admin.importar'
import { Route as NoticiasTagTagRouteImport } from './routes/noticias.tag.$tag'
import { Route as NoticiasCategoriaCategoryRouteImport } from './routes/noticias.categoria.$category'
import { Route as ApiPublicSitemapRouteImport } from './routes/api.public.sitemap'
import { Route as ApiPublicRssRouteImport } from './routes/api.public.rss'
import { Route as AdminNoticiasNovaRouteImport } from './routes/admin.noticias.nova'
import { Route as AdminNoticiasIdRouteImport } from './routes/admin.noticias.$id'

const TrabalhosRealizadosRoute = TrabalhosRealizadosRouteImport.update({
  id: '/trabalhos-realizados',
  path: '/trabalhos-realizados',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesWebRoute = SolucoesWebRouteImport.update({
  id: '/solucoes-web',
  path: '/solucoes-web',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaSobDemandaNcBrasilRoute =
  SistemaSobDemandaNcBrasilRouteImport.update({
    id: '/sistema-sob-demanda-nc-brasil',
    path: '/sistema-sob-demanda-nc-brasil',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemaDeRifasRoute = SistemaDeRifasRouteImport.update({
  id: '/sistema-de-rifas',
  path: '/sistema-de-rifas',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaDeRevendaDeVeiculosRoute =
  SistemaDeRevendaDeVeiculosRouteImport.update({
    id: '/sistema-de-revenda-de-veiculos',
    path: '/sistema-de-revenda-de-veiculos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemaDeRaspadinhaRoute = SistemaDeRaspadinhaRouteImport.update({
  id: '/sistema-de-raspadinha',
  path: '/sistema-de-raspadinha',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaDeOfertasCupomMarketplaceRoute =
  SistemaDeOfertasCupomMarketplaceRouteImport.update({
    id: '/sistema-de-ofertas-cupom-marketplace',
    path: '/sistema-de-ofertas-cupom-marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemaDeLeilaoRuralRoute = SistemaDeLeilaoRuralRouteImport.update({
  id: '/sistema-de-leilao-rural',
  path: '/sistema-de-leilao-rural',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaDeLeilaoDeCentavosRoute =
  SistemaDeLeilaoDeCentavosRouteImport.update({
    id: '/sistema-de-leilao-de-centavos',
    path: '/sistema-de-leilao-de-centavos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SistemaDeLeilaoRoute = SistemaDeLeilaoRouteImport.update({
  id: '/sistema-de-leilao',
  path: '/sistema-de-leilao',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaDeCupomDescontosRoute = SistemaDeCupomDescontosRouteImport.update({
  id: '/sistema-de-cupom-descontos',
  path: '/sistema-de-cupom-descontos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaDeOrdemDeServicoRoute =
  ProgramaDeOrdemDeServicoRouteImport.update({
    id: '/programa-de-ordem-de-servico',
    path: '/programa-de-ordem-de-servico',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlataformaChinesaApostasCassinoRoute =
  PlataformaChinesaApostasCassinoRouteImport.update({
    id: '/plataforma-chinesa-apostas-cassino',
    path: '/plataforma-chinesa-apostas-cassino',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const NossosSistemasRoute = NossosSistemasRouteImport.update({
  id: '/nossos-sistemas',
  path: '/nossos-sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const NossosServicosRoute = NossosServicosRouteImport.update({
  id: '/nossos-servicos',
  path: '/nossos-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramParaEmpresasRoute = InstagramParaEmpresasRouteImport.update({
  id: '/instagram-para-empresas',
  path: '/instagram-para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosNaCriacaoDeUmAplicativoRoute =
  ErrosNaCriacaoDeUmAplicativoRouteImport.update({
    id: '/erros-na-criacao-de-um-aplicativo',
    path: '/erros-na-criacao-de-um-aplicativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasParaECommerceRoute = DicasParaECommerceRouteImport.update({
  id: '/dicas-para-e-commerce',
  path: '/dicas-para-e-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificadosDeVeiculosRoute = ClassificadosDeVeiculosRouteImport.update({
  id: '/classificados-de-veiculos',
  path: '/classificados-de-veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasIndexRoute = SistemasIndexRouteImport.update({
  id: '/sistemas/',
  path: '/sistemas/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SolucoesWebSeoGoogleRoute = SolucoesWebSeoGoogleRouteImport.update({
  id: '/seo-google',
  path: '/seo-google',
  getParentRoute: () => SolucoesWebRoute,
} as any)
const SolucoesWebMarketingDigitalRoute =
  SolucoesWebMarketingDigitalRouteImport.update({
    id: '/marketing-digital',
    path: '/marketing-digital',
    getParentRoute: () => SolucoesWebRoute,
  } as any)
const SolucoesWebLojaVirtualRoute = SolucoesWebLojaVirtualRouteImport.update({
  id: '/loja-virtual',
  path: '/loja-virtual',
  getParentRoute: () => SolucoesWebRoute,
} as any)
const SolucoesWebLandingPagesRoute = SolucoesWebLandingPagesRouteImport.update({
  id: '/landing-pages',
  path: '/landing-pages',
  getParentRoute: () => SolucoesWebRoute,
} as any)
const SolucoesWebHospedagemRoute = SolucoesWebHospedagemRouteImport.update({
  id: '/hospedagem',
  path: '/hospedagem',
  getParentRoute: () => SolucoesWebRoute,
} as any)
const SolucoesWebDesenvolvimentoDeSitesRoute =
  SolucoesWebDesenvolvimentoDeSitesRouteImport.update({
    id: '/desenvolvimento-de-sites',
    path: '/desenvolvimento-de-sites',
    getParentRoute: () => SolucoesWebRoute,
  } as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasSlugRoute = SistemasSlugRouteImport.update({
  id: '/sistemas/$slug',
  path: '/sistemas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSistemasWebRoute = ServicosSistemasWebRouteImport.update({
  id: '/servicos/sistemas-web',
  path: '/servicos/sistemas-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIdentidadeVisualRoute =
  ServicosIdentidadeVisualRouteImport.update({
    id: '/servicos/identidade-visual',
    path: '/servicos/identidade-visual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosGoogleAdsRoute = ServicosGoogleAdsRouteImport.update({
  id: '/servicos/google-ads',
  path: '/servicos/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosFacebookAdsRoute = ServicosFacebookAdsRouteImport.update({
  id: '/servicos/facebook-ads',
  path: '/servicos/facebook-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosDesenvolvimentoRoute = ServicosDesenvolvimentoRouteImport.update({
  id: '/servicos/desenvolvimento',
  path: '/servicos/desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosConsultoriaRoute = ServicosConsultoriaRouteImport.update({
  id: '/servicos/consultoria',
  path: '/servicos/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosAplicativosRoute = ServicosAplicativosRouteImport.update({
  id: '/servicos/aplicativos',
  path: '/servicos/aplicativos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSitesCriadosRoute = PortfolioSitesCriadosRouteImport.update({
  id: '/portfolio/sites-criados',
  path: '/portfolio/sites-criados',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSistemasCriadosRoute =
  PortfolioSistemasCriadosRouteImport.update({
    id: '/portfolio/sistemas-criados',
    path: '/portfolio/sistemas-criados',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioSistemaDeCompraColetivaRoute =
  PortfolioSistemaDeCompraColetivaRouteImport.update({
    id: '/portfolio/sistema-de-compra-coletiva',
    path: '/portfolio/sistema-de-compra-coletiva',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioLojasVirtuaisCriadasRoute =
  PortfolioLojasVirtuaisCriadasRouteImport.update({
    id: '/portfolio/lojas-virtuais-criadas',
    path: '/portfolio/lojas-virtuais-criadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioLogotiposCriadosRoute =
  PortfolioLogotiposCriadosRouteImport.update({
    id: '/portfolio/logotipos-criados',
    path: '/portfolio/logotipos-criados',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioIdentidadeVisualRoute =
  PortfolioIdentidadeVisualRouteImport.update({
    id: '/portfolio/identidade-visual',
    path: '/portfolio/identidade-visual',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCriacaoDeSistemasRoute =
  PortfolioCriacaoDeSistemasRouteImport.update({
    id: '/portfolio/criacao-de-sistemas',
    path: '/portfolio/criacao-de-sistemas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCriacaoDeLogomarcasRoute =
  PortfolioCriacaoDeLogomarcasRouteImport.update({
    id: '/portfolio/criacao-de-logomarcas',
    path: '/portfolio/criacao-de-logomarcas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCriacaoDeAplicativosRoute =
  PortfolioCriacaoDeAplicativosRouteImport.update({
    id: '/portfolio/criacao-de-aplicativos',
    path: '/portfolio/criacao-de-aplicativos',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioAplicativosCriadosRoute =
  PortfolioAplicativosCriadosRouteImport.update({
    id: '/portfolio/aplicativos-criados',
    path: '/portfolio/aplicativos-criados',
    getParentRoute: () => rootRouteImport,
  } as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaQuemSomosRoute = EmpresaQuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaNossaHistoriaRoute = EmpresaNossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaClientesRoute = EmpresaClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => EmpresaRoute,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportarRoute = AdminImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AdminRoute,
} as any)
const NoticiasTagTagRoute = NoticiasTagTagRouteImport.update({
  id: '/noticias/tag/$tag',
  path: '/noticias/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasCategoriaCategoryRoute =
  NoticiasCategoriaCategoryRouteImport.update({
    id: '/noticias/categoria/$category',
    path: '/noticias/categoria/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRssRoute = ApiPublicRssRouteImport.update({
  id: '/api/public/rss',
  path: '/api/public/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticiasNovaRoute = AdminNoticiasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminNoticiasRoute,
} as any)
const AdminNoticiasIdRoute = AdminNoticiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNoticiasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classificados-de-veiculos': typeof ClassificadosDeVeiculosRoute
  '/contato': typeof ContatoRoute
  '/dicas-para-e-commerce': typeof DicasParaECommerceRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/erros-na-criacao-de-um-aplicativo': typeof ErrosNaCriacaoDeUmAplicativoRoute
  '/instagram-para-empresas': typeof InstagramParaEmpresasRoute
  '/nossos-servicos': typeof NossosServicosRoute
  '/nossos-sistemas': typeof NossosSistemasRoute
  '/orcamento': typeof OrcamentoRoute
  '/plataforma-chinesa-apostas-cassino': typeof PlataformaChinesaApostasCassinoRoute
  '/programa-de-ordem-de-servico': typeof ProgramaDeOrdemDeServicoRoute
  '/sistema-de-cupom-descontos': typeof SistemaDeCupomDescontosRoute
  '/sistema-de-leilao': typeof SistemaDeLeilaoRoute
  '/sistema-de-leilao-de-centavos': typeof SistemaDeLeilaoDeCentavosRoute
  '/sistema-de-leilao-rural': typeof SistemaDeLeilaoRuralRoute
  '/sistema-de-ofertas-cupom-marketplace': typeof SistemaDeOfertasCupomMarketplaceRoute
  '/sistema-de-raspadinha': typeof SistemaDeRaspadinhaRoute
  '/sistema-de-revenda-de-veiculos': typeof SistemaDeRevendaDeVeiculosRoute
  '/sistema-de-rifas': typeof SistemaDeRifasRoute
  '/sistema-sob-demanda-nc-brasil': typeof SistemaSobDemandaNcBrasilRoute
  '/software': typeof SoftwareRoute
  '/solucoes-web': typeof SolucoesWebRouteWithChildren
  '/trabalhos-realizados': typeof TrabalhosRealizadosRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/noticias': typeof AdminNoticiasRouteWithChildren
  '/empresa/clientes': typeof EmpresaClientesRoute
  '/empresa/nossa-historia': typeof EmpresaNossaHistoriaRoute
  '/empresa/quem-somos': typeof EmpresaQuemSomosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/portfolio/aplicativos-criados': typeof PortfolioAplicativosCriadosRoute
  '/portfolio/criacao-de-aplicativos': typeof PortfolioCriacaoDeAplicativosRoute
  '/portfolio/criacao-de-logomarcas': typeof PortfolioCriacaoDeLogomarcasRoute
  '/portfolio/criacao-de-sistemas': typeof PortfolioCriacaoDeSistemasRoute
  '/portfolio/identidade-visual': typeof PortfolioIdentidadeVisualRoute
  '/portfolio/logotipos-criados': typeof PortfolioLogotiposCriadosRoute
  '/portfolio/lojas-virtuais-criadas': typeof PortfolioLojasVirtuaisCriadasRoute
  '/portfolio/sistema-de-compra-coletiva': typeof PortfolioSistemaDeCompraColetivaRoute
  '/portfolio/sistemas-criados': typeof PortfolioSistemasCriadosRoute
  '/portfolio/sites-criados': typeof PortfolioSitesCriadosRoute
  '/servicos/aplicativos': typeof ServicosAplicativosRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/desenvolvimento': typeof ServicosDesenvolvimentoRoute
  '/servicos/facebook-ads': typeof ServicosFacebookAdsRoute
  '/servicos/google-ads': typeof ServicosGoogleAdsRoute
  '/servicos/identidade-visual': typeof ServicosIdentidadeVisualRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/sistemas/$slug': typeof SistemasSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/solucoes-web/desenvolvimento-de-sites': typeof SolucoesWebDesenvolvimentoDeSitesRoute
  '/solucoes-web/hospedagem': typeof SolucoesWebHospedagemRoute
  '/solucoes-web/landing-pages': typeof SolucoesWebLandingPagesRoute
  '/solucoes-web/loja-virtual': typeof SolucoesWebLojaVirtualRoute
  '/solucoes-web/marketing-digital': typeof SolucoesWebMarketingDigitalRoute
  '/solucoes-web/seo-google': typeof SolucoesWebSeoGoogleRoute
  '/admin/': typeof AdminIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/sistemas/': typeof SistemasIndexRoute
  '/admin/noticias/$id': typeof AdminNoticiasIdRoute
  '/admin/noticias/nova': typeof AdminNoticiasNovaRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/noticias/categoria/$category': typeof NoticiasCategoriaCategoryRoute
  '/noticias/tag/$tag': typeof NoticiasTagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificados-de-veiculos': typeof ClassificadosDeVeiculosRoute
  '/contato': typeof ContatoRoute
  '/dicas-para-e-commerce': typeof DicasParaECommerceRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/erros-na-criacao-de-um-aplicativo': typeof ErrosNaCriacaoDeUmAplicativoRoute
  '/instagram-para-empresas': typeof InstagramParaEmpresasRoute
  '/nossos-servicos': typeof NossosServicosRoute
  '/nossos-sistemas': typeof NossosSistemasRoute
  '/orcamento': typeof OrcamentoRoute
  '/plataforma-chinesa-apostas-cassino': typeof PlataformaChinesaApostasCassinoRoute
  '/programa-de-ordem-de-servico': typeof ProgramaDeOrdemDeServicoRoute
  '/sistema-de-cupom-descontos': typeof SistemaDeCupomDescontosRoute
  '/sistema-de-leilao': typeof SistemaDeLeilaoRoute
  '/sistema-de-leilao-de-centavos': typeof SistemaDeLeilaoDeCentavosRoute
  '/sistema-de-leilao-rural': typeof SistemaDeLeilaoRuralRoute
  '/sistema-de-ofertas-cupom-marketplace': typeof SistemaDeOfertasCupomMarketplaceRoute
  '/sistema-de-raspadinha': typeof SistemaDeRaspadinhaRoute
  '/sistema-de-revenda-de-veiculos': typeof SistemaDeRevendaDeVeiculosRoute
  '/sistema-de-rifas': typeof SistemaDeRifasRoute
  '/sistema-sob-demanda-nc-brasil': typeof SistemaSobDemandaNcBrasilRoute
  '/software': typeof SoftwareRoute
  '/solucoes-web': typeof SolucoesWebRouteWithChildren
  '/trabalhos-realizados': typeof TrabalhosRealizadosRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/noticias': typeof AdminNoticiasRouteWithChildren
  '/empresa/clientes': typeof EmpresaClientesRoute
  '/empresa/nossa-historia': typeof EmpresaNossaHistoriaRoute
  '/empresa/quem-somos': typeof EmpresaQuemSomosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/portfolio/aplicativos-criados': typeof PortfolioAplicativosCriadosRoute
  '/portfolio/criacao-de-aplicativos': typeof PortfolioCriacaoDeAplicativosRoute
  '/portfolio/criacao-de-logomarcas': typeof PortfolioCriacaoDeLogomarcasRoute
  '/portfolio/criacao-de-sistemas': typeof PortfolioCriacaoDeSistemasRoute
  '/portfolio/identidade-visual': typeof PortfolioIdentidadeVisualRoute
  '/portfolio/logotipos-criados': typeof PortfolioLogotiposCriadosRoute
  '/portfolio/lojas-virtuais-criadas': typeof PortfolioLojasVirtuaisCriadasRoute
  '/portfolio/sistema-de-compra-coletiva': typeof PortfolioSistemaDeCompraColetivaRoute
  '/portfolio/sistemas-criados': typeof PortfolioSistemasCriadosRoute
  '/portfolio/sites-criados': typeof PortfolioSitesCriadosRoute
  '/servicos/aplicativos': typeof ServicosAplicativosRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/desenvolvimento': typeof ServicosDesenvolvimentoRoute
  '/servicos/facebook-ads': typeof ServicosFacebookAdsRoute
  '/servicos/google-ads': typeof ServicosGoogleAdsRoute
  '/servicos/identidade-visual': typeof ServicosIdentidadeVisualRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/sistemas/$slug': typeof SistemasSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/solucoes-web/desenvolvimento-de-sites': typeof SolucoesWebDesenvolvimentoDeSitesRoute
  '/solucoes-web/hospedagem': typeof SolucoesWebHospedagemRoute
  '/solucoes-web/landing-pages': typeof SolucoesWebLandingPagesRoute
  '/solucoes-web/loja-virtual': typeof SolucoesWebLojaVirtualRoute
  '/solucoes-web/marketing-digital': typeof SolucoesWebMarketingDigitalRoute
  '/solucoes-web/seo-google': typeof SolucoesWebSeoGoogleRoute
  '/admin': typeof AdminIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/sistemas': typeof SistemasIndexRoute
  '/admin/noticias/$id': typeof AdminNoticiasIdRoute
  '/admin/noticias/nova': typeof AdminNoticiasNovaRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/noticias/categoria/$category': typeof NoticiasCategoriaCategoryRoute
  '/noticias/tag/$tag': typeof NoticiasTagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classificados-de-veiculos': typeof ClassificadosDeVeiculosRoute
  '/contato': typeof ContatoRoute
  '/dicas-para-e-commerce': typeof DicasParaECommerceRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/erros-na-criacao-de-um-aplicativo': typeof ErrosNaCriacaoDeUmAplicativoRoute
  '/instagram-para-empresas': typeof InstagramParaEmpresasRoute
  '/nossos-servicos': typeof NossosServicosRoute
  '/nossos-sistemas': typeof NossosSistemasRoute
  '/orcamento': typeof OrcamentoRoute
  '/plataforma-chinesa-apostas-cassino': typeof PlataformaChinesaApostasCassinoRoute
  '/programa-de-ordem-de-servico': typeof ProgramaDeOrdemDeServicoRoute
  '/sistema-de-cupom-descontos': typeof SistemaDeCupomDescontosRoute
  '/sistema-de-leilao': typeof SistemaDeLeilaoRoute
  '/sistema-de-leilao-de-centavos': typeof SistemaDeLeilaoDeCentavosRoute
  '/sistema-de-leilao-rural': typeof SistemaDeLeilaoRuralRoute
  '/sistema-de-ofertas-cupom-marketplace': typeof SistemaDeOfertasCupomMarketplaceRoute
  '/sistema-de-raspadinha': typeof SistemaDeRaspadinhaRoute
  '/sistema-de-revenda-de-veiculos': typeof SistemaDeRevendaDeVeiculosRoute
  '/sistema-de-rifas': typeof SistemaDeRifasRoute
  '/sistema-sob-demanda-nc-brasil': typeof SistemaSobDemandaNcBrasilRoute
  '/software': typeof SoftwareRoute
  '/solucoes-web': typeof SolucoesWebRouteWithChildren
  '/trabalhos-realizados': typeof TrabalhosRealizadosRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/noticias': typeof AdminNoticiasRouteWithChildren
  '/empresa/clientes': typeof EmpresaClientesRoute
  '/empresa/nossa-historia': typeof EmpresaNossaHistoriaRoute
  '/empresa/quem-somos': typeof EmpresaQuemSomosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/portfolio/aplicativos-criados': typeof PortfolioAplicativosCriadosRoute
  '/portfolio/criacao-de-aplicativos': typeof PortfolioCriacaoDeAplicativosRoute
  '/portfolio/criacao-de-logomarcas': typeof PortfolioCriacaoDeLogomarcasRoute
  '/portfolio/criacao-de-sistemas': typeof PortfolioCriacaoDeSistemasRoute
  '/portfolio/identidade-visual': typeof PortfolioIdentidadeVisualRoute
  '/portfolio/logotipos-criados': typeof PortfolioLogotiposCriadosRoute
  '/portfolio/lojas-virtuais-criadas': typeof PortfolioLojasVirtuaisCriadasRoute
  '/portfolio/sistema-de-compra-coletiva': typeof PortfolioSistemaDeCompraColetivaRoute
  '/portfolio/sistemas-criados': typeof PortfolioSistemasCriadosRoute
  '/portfolio/sites-criados': typeof PortfolioSitesCriadosRoute
  '/servicos/aplicativos': typeof ServicosAplicativosRoute
  '/servicos/consultoria': typeof ServicosConsultoriaRoute
  '/servicos/desenvolvimento': typeof ServicosDesenvolvimentoRoute
  '/servicos/facebook-ads': typeof ServicosFacebookAdsRoute
  '/servicos/google-ads': typeof ServicosGoogleAdsRoute
  '/servicos/identidade-visual': typeof ServicosIdentidadeVisualRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/sistemas/$slug': typeof SistemasSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/solucoes-web/desenvolvimento-de-sites': typeof SolucoesWebDesenvolvimentoDeSitesRoute
  '/solucoes-web/hospedagem': typeof SolucoesWebHospedagemRoute
  '/solucoes-web/landing-pages': typeof SolucoesWebLandingPagesRoute
  '/solucoes-web/loja-virtual': typeof SolucoesWebLojaVirtualRoute
  '/solucoes-web/marketing-digital': typeof SolucoesWebMarketingDigitalRoute
  '/solucoes-web/seo-google': typeof SolucoesWebSeoGoogleRoute
  '/admin/': typeof AdminIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/sistemas/': typeof SistemasIndexRoute
  '/admin/noticias/$id': typeof AdminNoticiasIdRoute
  '/admin/noticias/nova': typeof AdminNoticiasNovaRoute
  '/api/public/rss': typeof ApiPublicRssRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
  '/noticias/categoria/$category': typeof NoticiasCategoriaCategoryRoute
  '/noticias/tag/$tag': typeof NoticiasTagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/classificados-de-veiculos'
    | '/contato'
    | '/dicas-para-e-commerce'
    | '/empresa'
    | '/erros-na-criacao-de-um-aplicativo'
    | '/instagram-para-empresas'
    | '/nossos-servicos'
    | '/nossos-sistemas'
    | '/orcamento'
    | '/plataforma-chinesa-apostas-cassino'
    | '/programa-de-ordem-de-servico'
    | '/sistema-de-cupom-descontos'
    | '/sistema-de-leilao'
    | '/sistema-de-leilao-de-centavos'
    | '/sistema-de-leilao-rural'
    | '/sistema-de-ofertas-cupom-marketplace'
    | '/sistema-de-raspadinha'
    | '/sistema-de-revenda-de-veiculos'
    | '/sistema-de-rifas'
    | '/sistema-sob-demanda-nc-brasil'
    | '/software'
    | '/solucoes-web'
    | '/trabalhos-realizados'
    | '/admin/importar'
    | '/admin/noticias'
    | '/empresa/clientes'
    | '/empresa/nossa-historia'
    | '/empresa/quem-somos'
    | '/noticias/$slug'
    | '/portfolio/aplicativos-criados'
    | '/portfolio/criacao-de-aplicativos'
    | '/portfolio/criacao-de-logomarcas'
    | '/portfolio/criacao-de-sistemas'
    | '/portfolio/identidade-visual'
    | '/portfolio/logotipos-criados'
    | '/portfolio/lojas-virtuais-criadas'
    | '/portfolio/sistema-de-compra-coletiva'
    | '/portfolio/sistemas-criados'
    | '/portfolio/sites-criados'
    | '/servicos/aplicativos'
    | '/servicos/consultoria'
    | '/servicos/desenvolvimento'
    | '/servicos/facebook-ads'
    | '/servicos/google-ads'
    | '/servicos/identidade-visual'
    | '/servicos/sistemas-web'
    | '/sistemas/$slug'
    | '/sitemap/xml'
    | '/solucoes-web/desenvolvimento-de-sites'
    | '/solucoes-web/hospedagem'
    | '/solucoes-web/landing-pages'
    | '/solucoes-web/loja-virtual'
    | '/solucoes-web/marketing-digital'
    | '/solucoes-web/seo-google'
    | '/admin/'
    | '/noticias/'
    | '/sistemas/'
    | '/admin/noticias/$id'
    | '/admin/noticias/nova'
    | '/api/public/rss'
    | '/api/public/sitemap'
    | '/noticias/categoria/$category'
    | '/noticias/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classificados-de-veiculos'
    | '/contato'
    | '/dicas-para-e-commerce'
    | '/empresa'
    | '/erros-na-criacao-de-um-aplicativo'
    | '/instagram-para-empresas'
    | '/nossos-servicos'
    | '/nossos-sistemas'
    | '/orcamento'
    | '/plataforma-chinesa-apostas-cassino'
    | '/programa-de-ordem-de-servico'
    | '/sistema-de-cupom-descontos'
    | '/sistema-de-leilao'
    | '/sistema-de-leilao-de-centavos'
    | '/sistema-de-leilao-rural'
    | '/sistema-de-ofertas-cupom-marketplace'
    | '/sistema-de-raspadinha'
    | '/sistema-de-revenda-de-veiculos'
    | '/sistema-de-rifas'
    | '/sistema-sob-demanda-nc-brasil'
    | '/software'
    | '/solucoes-web'
    | '/trabalhos-realizados'
    | '/admin/importar'
    | '/admin/noticias'
    | '/empresa/clientes'
    | '/empresa/nossa-historia'
    | '/empresa/quem-somos'
    | '/noticias/$slug'
    | '/portfolio/aplicativos-criados'
    | '/portfolio/criacao-de-aplicativos'
    | '/portfolio/criacao-de-logomarcas'
    | '/portfolio/criacao-de-sistemas'
    | '/portfolio/identidade-visual'
    | '/portfolio/logotipos-criados'
    | '/portfolio/lojas-virtuais-criadas'
    | '/portfolio/sistema-de-compra-coletiva'
    | '/portfolio/sistemas-criados'
    | '/portfolio/sites-criados'
    | '/servicos/aplicativos'
    | '/servicos/consultoria'
    | '/servicos/desenvolvimento'
    | '/servicos/facebook-ads'
    | '/servicos/google-ads'
    | '/servicos/identidade-visual'
    | '/servicos/sistemas-web'
    | '/sistemas/$slug'
    | '/sitemap/xml'
    | '/solucoes-web/desenvolvimento-de-sites'
    | '/solucoes-web/hospedagem'
    | '/solucoes-web/landing-pages'
    | '/solucoes-web/loja-virtual'
    | '/solucoes-web/marketing-digital'
    | '/solucoes-web/seo-google'
    | '/admin'
    | '/noticias'
    | '/sistemas'
    | '/admin/noticias/$id'
    | '/admin/noticias/nova'
    | '/api/public/rss'
    | '/api/public/sitemap'
    | '/noticias/categoria/$category'
    | '/noticias/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/classificados-de-veiculos'
    | '/contato'
    | '/dicas-para-e-commerce'
    | '/empresa'
    | '/erros-na-criacao-de-um-aplicativo'
    | '/instagram-para-empresas'
    | '/nossos-servicos'
    | '/nossos-sistemas'
    | '/orcamento'
    | '/plataforma-chinesa-apostas-cassino'
    | '/programa-de-ordem-de-servico'
    | '/sistema-de-cupom-descontos'
    | '/sistema-de-leilao'
    | '/sistema-de-leilao-de-centavos'
    | '/sistema-de-leilao-rural'
    | '/sistema-de-ofertas-cupom-marketplace'
    | '/sistema-de-raspadinha'
    | '/sistema-de-revenda-de-veiculos'
    | '/sistema-de-rifas'
    | '/sistema-sob-demanda-nc-brasil'
    | '/software'
    | '/solucoes-web'
    | '/trabalhos-realizados'
    | '/admin/importar'
    | '/admin/noticias'
    | '/empresa/clientes'
    | '/empresa/nossa-historia'
    | '/empresa/quem-somos'
    | '/noticias/$slug'
    | '/portfolio/aplicativos-criados'
    | '/portfolio/criacao-de-aplicativos'
    | '/portfolio/criacao-de-logomarcas'
    | '/portfolio/criacao-de-sistemas'
    | '/portfolio/identidade-visual'
    | '/portfolio/logotipos-criados'
    | '/portfolio/lojas-virtuais-criadas'
    | '/portfolio/sistema-de-compra-coletiva'
    | '/portfolio/sistemas-criados'
    | '/portfolio/sites-criados'
    | '/servicos/aplicativos'
    | '/servicos/consultoria'
    | '/servicos/desenvolvimento'
    | '/servicos/facebook-ads'
    | '/servicos/google-ads'
    | '/servicos/identidade-visual'
    | '/servicos/sistemas-web'
    | '/sistemas/$slug'
    | '/sitemap/xml'
    | '/solucoes-web/desenvolvimento-de-sites'
    | '/solucoes-web/hospedagem'
    | '/solucoes-web/landing-pages'
    | '/solucoes-web/loja-virtual'
    | '/solucoes-web/marketing-digital'
    | '/solucoes-web/seo-google'
    | '/admin/'
    | '/noticias/'
    | '/sistemas/'
    | '/admin/noticias/$id'
    | '/admin/noticias/nova'
    | '/api/public/rss'
    | '/api/public/sitemap'
    | '/noticias/categoria/$category'
    | '/noticias/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClassificadosDeVeiculosRoute: typeof ClassificadosDeVeiculosRoute
  ContatoRoute: typeof ContatoRoute
  DicasParaECommerceRoute: typeof DicasParaECommerceRoute
  EmpresaRoute: typeof EmpresaRouteWithChildren
  ErrosNaCriacaoDeUmAplicativoRoute: typeof ErrosNaCriacaoDeUmAplicativoRoute
  InstagramParaEmpresasRoute: typeof InstagramParaEmpresasRoute
  NossosServicosRoute: typeof NossosServicosRoute
  NossosSistemasRoute: typeof NossosSistemasRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PlataformaChinesaApostasCassinoRoute: typeof PlataformaChinesaApostasCassinoRoute
  ProgramaDeOrdemDeServicoRoute: typeof ProgramaDeOrdemDeServicoRoute
  SistemaDeCupomDescontosRoute: typeof SistemaDeCupomDescontosRoute
  SistemaDeLeilaoRoute: typeof SistemaDeLeilaoRoute
  SistemaDeLeilaoDeCentavosRoute: typeof SistemaDeLeilaoDeCentavosRoute
  SistemaDeLeilaoRuralRoute: typeof SistemaDeLeilaoRuralRoute
  SistemaDeOfertasCupomMarketplaceRoute: typeof SistemaDeOfertasCupomMarketplaceRoute
  SistemaDeRaspadinhaRoute: typeof SistemaDeRaspadinhaRoute
  SistemaDeRevendaDeVeiculosRoute: typeof SistemaDeRevendaDeVeiculosRoute
  SistemaDeRifasRoute: typeof SistemaDeRifasRoute
  SistemaSobDemandaNcBrasilRoute: typeof SistemaSobDemandaNcBrasilRoute
  SoftwareRoute: typeof SoftwareRoute
  SolucoesWebRoute: typeof SolucoesWebRouteWithChildren
  TrabalhosRealizadosRoute: typeof TrabalhosRealizadosRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  PortfolioAplicativosCriadosRoute: typeof PortfolioAplicativosCriadosRoute
  PortfolioCriacaoDeAplicativosRoute: typeof PortfolioCriacaoDeAplicativosRoute
  PortfolioCriacaoDeLogomarcasRoute: typeof PortfolioCriacaoDeLogomarcasRoute
  PortfolioCriacaoDeSistemasRoute: typeof PortfolioCriacaoDeSistemasRoute
  PortfolioIdentidadeVisualRoute: typeof PortfolioIdentidadeVisualRoute
  PortfolioLogotiposCriadosRoute: typeof PortfolioLogotiposCriadosRoute
  PortfolioLojasVirtuaisCriadasRoute: typeof PortfolioLojasVirtuaisCriadasRoute
  PortfolioSistemaDeCompraColetivaRoute: typeof PortfolioSistemaDeCompraColetivaRoute
  PortfolioSistemasCriadosRoute: typeof PortfolioSistemasCriadosRoute
  PortfolioSitesCriadosRoute: typeof PortfolioSitesCriadosRoute
  ServicosAplicativosRoute: typeof ServicosAplicativosRoute
  ServicosConsultoriaRoute: typeof ServicosConsultoriaRoute
  ServicosDesenvolvimentoRoute: typeof ServicosDesenvolvimentoRoute
  ServicosFacebookAdsRoute: typeof ServicosFacebookAdsRoute
  ServicosGoogleAdsRoute: typeof ServicosGoogleAdsRoute
  ServicosIdentidadeVisualRoute: typeof ServicosIdentidadeVisualRoute
  ServicosSistemasWebRoute: typeof ServicosSistemasWebRoute
  SistemasSlugRoute: typeof SistemasSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  SistemasIndexRoute: typeof SistemasIndexRoute
  ApiPublicRssRoute: typeof ApiPublicRssRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
  NoticiasCategoriaCategoryRoute: typeof NoticiasCategoriaCategoryRoute
  NoticiasTagTagRoute: typeof NoticiasTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhos-realizados': {
      id: '/trabalhos-realizados'
      path: '/trabalhos-realizados'
      fullPath: '/trabalhos-realizados'
      preLoaderRoute: typeof TrabalhosRealizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes-web': {
      id: '/solucoes-web'
      path: '/solucoes-web'
      fullPath: '/solucoes-web'
      preLoaderRoute: typeof SolucoesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-sob-demanda-nc-brasil': {
      id: '/sistema-sob-demanda-nc-brasil'
      path: '/sistema-sob-demanda-nc-brasil'
      fullPath: '/sistema-sob-demanda-nc-brasil'
      preLoaderRoute: typeof SistemaSobDemandaNcBrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-rifas': {
      id: '/sistema-de-rifas'
      path: '/sistema-de-rifas'
      fullPath: '/sistema-de-rifas'
      preLoaderRoute: typeof SistemaDeRifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-revenda-de-veiculos': {
      id: '/sistema-de-revenda-de-veiculos'
      path: '/sistema-de-revenda-de-veiculos'
      fullPath: '/sistema-de-revenda-de-veiculos'
      preLoaderRoute: typeof SistemaDeRevendaDeVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-raspadinha': {
      id: '/sistema-de-raspadinha'
      path: '/sistema-de-raspadinha'
      fullPath: '/sistema-de-raspadinha'
      preLoaderRoute: typeof SistemaDeRaspadinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-ofertas-cupom-marketplace': {
      id: '/sistema-de-ofertas-cupom-marketplace'
      path: '/sistema-de-ofertas-cupom-marketplace'
      fullPath: '/sistema-de-ofertas-cupom-marketplace'
      preLoaderRoute: typeof SistemaDeOfertasCupomMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-leilao-rural': {
      id: '/sistema-de-leilao-rural'
      path: '/sistema-de-leilao-rural'
      fullPath: '/sistema-de-leilao-rural'
      preLoaderRoute: typeof SistemaDeLeilaoRuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-leilao-de-centavos': {
      id: '/sistema-de-leilao-de-centavos'
      path: '/sistema-de-leilao-de-centavos'
      fullPath: '/sistema-de-leilao-de-centavos'
      preLoaderRoute: typeof SistemaDeLeilaoDeCentavosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-leilao': {
      id: '/sistema-de-leilao'
      path: '/sistema-de-leilao'
      fullPath: '/sistema-de-leilao'
      preLoaderRoute: typeof SistemaDeLeilaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-de-cupom-descontos': {
      id: '/sistema-de-cupom-descontos'
      path: '/sistema-de-cupom-descontos'
      fullPath: '/sistema-de-cupom-descontos'
      preLoaderRoute: typeof SistemaDeCupomDescontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-ordem-de-servico': {
      id: '/programa-de-ordem-de-servico'
      path: '/programa-de-ordem-de-servico'
      fullPath: '/programa-de-ordem-de-servico'
      preLoaderRoute: typeof ProgramaDeOrdemDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma-chinesa-apostas-cassino': {
      id: '/plataforma-chinesa-apostas-cassino'
      path: '/plataforma-chinesa-apostas-cassino'
      fullPath: '/plataforma-chinesa-apostas-cassino'
      preLoaderRoute: typeof PlataformaChinesaApostasCassinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossos-sistemas': {
      id: '/nossos-sistemas'
      path: '/nossos-sistemas'
      fullPath: '/nossos-sistemas'
      preLoaderRoute: typeof NossosSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossos-servicos': {
      id: '/nossos-servicos'
      path: '/nossos-servicos'
      fullPath: '/nossos-servicos'
      preLoaderRoute: typeof NossosServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-para-empresas': {
      id: '/instagram-para-empresas'
      path: '/instagram-para-empresas'
      fullPath: '/instagram-para-empresas'
      preLoaderRoute: typeof InstagramParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros-na-criacao-de-um-aplicativo': {
      id: '/erros-na-criacao-de-um-aplicativo'
      path: '/erros-na-criacao-de-um-aplicativo'
      fullPath: '/erros-na-criacao-de-um-aplicativo'
      preLoaderRoute: typeof ErrosNaCriacaoDeUmAplicativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas-para-e-commerce': {
      id: '/dicas-para-e-commerce'
      path: '/dicas-para-e-commerce'
      fullPath: '/dicas-para-e-commerce'
      preLoaderRoute: typeof DicasParaECommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificados-de-veiculos': {
      id: '/classificados-de-veiculos'
      path: '/classificados-de-veiculos'
      fullPath: '/classificados-de-veiculos'
      preLoaderRoute: typeof ClassificadosDeVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/': {
      id: '/sistemas/'
      path: '/sistemas'
      fullPath: '/sistemas/'
      preLoaderRoute: typeof SistemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/solucoes-web/seo-google': {
      id: '/solucoes-web/seo-google'
      path: '/seo-google'
      fullPath: '/solucoes-web/seo-google'
      preLoaderRoute: typeof SolucoesWebSeoGoogleRouteImport
      parentRoute: typeof SolucoesWebRoute
    }
    '/solucoes-web/marketing-digital': {
      id: '/solucoes-web/marketing-digital'
      path: '/marketing-digital'
      fullPath: '/solucoes-web/marketing-digital'
      preLoaderRoute: typeof SolucoesWebMarketingDigitalRouteImport
      parentRoute: typeof SolucoesWebRoute
    }
    '/solucoes-web/loja-virtual': {
      id: '/solucoes-web/loja-virtual'
      path: '/loja-virtual'
      fullPath: '/solucoes-web/loja-virtual'
      preLoaderRoute: typeof SolucoesWebLojaVirtualRouteImport
      parentRoute: typeof SolucoesWebRoute
    }
    '/solucoes-web/landing-pages': {
      id: '/solucoes-web/landing-pages'
      path: '/landing-pages'
      fullPath: '/solucoes-web/landing-pages'
      preLoaderRoute: typeof SolucoesWebLandingPagesRouteImport
      parentRoute: typeof SolucoesWebRoute
    }
    '/solucoes-web/hospedagem': {
      id: '/solucoes-web/hospedagem'
      path: '/hospedagem'
      fullPath: '/solucoes-web/hospedagem'
      preLoaderRoute: typeof SolucoesWebHospedagemRouteImport
      parentRoute: typeof SolucoesWebRoute
    }
    '/solucoes-web/desenvolvimento-de-sites': {
      id: '/solucoes-web/desenvolvimento-de-sites'
      path: '/desenvolvimento-de-sites'
      fullPath: '/solucoes-web/desenvolvimento-de-sites'
      preLoaderRoute: typeof SolucoesWebDesenvolvimentoDeSitesRouteImport
      parentRoute: typeof SolucoesWebRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas/$slug': {
      id: '/sistemas/$slug'
      path: '/sistemas/$slug'
      fullPath: '/sistemas/$slug'
      preLoaderRoute: typeof SistemasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/sistemas-web': {
      id: '/servicos/sistemas-web'
      path: '/servicos/sistemas-web'
      fullPath: '/servicos/sistemas-web'
      preLoaderRoute: typeof ServicosSistemasWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/identidade-visual': {
      id: '/servicos/identidade-visual'
      path: '/servicos/identidade-visual'
      fullPath: '/servicos/identidade-visual'
      preLoaderRoute: typeof ServicosIdentidadeVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/google-ads': {
      id: '/servicos/google-ads'
      path: '/servicos/google-ads'
      fullPath: '/servicos/google-ads'
      preLoaderRoute: typeof ServicosGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/facebook-ads': {
      id: '/servicos/facebook-ads'
      path: '/servicos/facebook-ads'
      fullPath: '/servicos/facebook-ads'
      preLoaderRoute: typeof ServicosFacebookAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/desenvolvimento': {
      id: '/servicos/desenvolvimento'
      path: '/servicos/desenvolvimento'
      fullPath: '/servicos/desenvolvimento'
      preLoaderRoute: typeof ServicosDesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/consultoria': {
      id: '/servicos/consultoria'
      path: '/servicos/consultoria'
      fullPath: '/servicos/consultoria'
      preLoaderRoute: typeof ServicosConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/aplicativos': {
      id: '/servicos/aplicativos'
      path: '/servicos/aplicativos'
      fullPath: '/servicos/aplicativos'
      preLoaderRoute: typeof ServicosAplicativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/sites-criados': {
      id: '/portfolio/sites-criados'
      path: '/portfolio/sites-criados'
      fullPath: '/portfolio/sites-criados'
      preLoaderRoute: typeof PortfolioSitesCriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/sistemas-criados': {
      id: '/portfolio/sistemas-criados'
      path: '/portfolio/sistemas-criados'
      fullPath: '/portfolio/sistemas-criados'
      preLoaderRoute: typeof PortfolioSistemasCriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/sistema-de-compra-coletiva': {
      id: '/portfolio/sistema-de-compra-coletiva'
      path: '/portfolio/sistema-de-compra-coletiva'
      fullPath: '/portfolio/sistema-de-compra-coletiva'
      preLoaderRoute: typeof PortfolioSistemaDeCompraColetivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/lojas-virtuais-criadas': {
      id: '/portfolio/lojas-virtuais-criadas'
      path: '/portfolio/lojas-virtuais-criadas'
      fullPath: '/portfolio/lojas-virtuais-criadas'
      preLoaderRoute: typeof PortfolioLojasVirtuaisCriadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/logotipos-criados': {
      id: '/portfolio/logotipos-criados'
      path: '/portfolio/logotipos-criados'
      fullPath: '/portfolio/logotipos-criados'
      preLoaderRoute: typeof PortfolioLogotiposCriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/identidade-visual': {
      id: '/portfolio/identidade-visual'
      path: '/portfolio/identidade-visual'
      fullPath: '/portfolio/identidade-visual'
      preLoaderRoute: typeof PortfolioIdentidadeVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/criacao-de-sistemas': {
      id: '/portfolio/criacao-de-sistemas'
      path: '/portfolio/criacao-de-sistemas'
      fullPath: '/portfolio/criacao-de-sistemas'
      preLoaderRoute: typeof PortfolioCriacaoDeSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/criacao-de-logomarcas': {
      id: '/portfolio/criacao-de-logomarcas'
      path: '/portfolio/criacao-de-logomarcas'
      fullPath: '/portfolio/criacao-de-logomarcas'
      preLoaderRoute: typeof PortfolioCriacaoDeLogomarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/criacao-de-aplicativos': {
      id: '/portfolio/criacao-de-aplicativos'
      path: '/portfolio/criacao-de-aplicativos'
      fullPath: '/portfolio/criacao-de-aplicativos'
      preLoaderRoute: typeof PortfolioCriacaoDeAplicativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/aplicativos-criados': {
      id: '/portfolio/aplicativos-criados'
      path: '/portfolio/aplicativos-criados'
      fullPath: '/portfolio/aplicativos-criados'
      preLoaderRoute: typeof PortfolioAplicativosCriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/quem-somos': {
      id: '/empresa/quem-somos'
      path: '/quem-somos'
      fullPath: '/empresa/quem-somos'
      preLoaderRoute: typeof EmpresaQuemSomosRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/nossa-historia': {
      id: '/empresa/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/empresa/nossa-historia'
      preLoaderRoute: typeof EmpresaNossaHistoriaRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/clientes': {
      id: '/empresa/clientes'
      path: '/clientes'
      fullPath: '/empresa/clientes'
      preLoaderRoute: typeof EmpresaClientesRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importar': {
      id: '/admin/importar'
      path: '/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AdminImportarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/noticias/tag/$tag': {
      id: '/noticias/tag/$tag'
      path: '/noticias/tag/$tag'
      fullPath: '/noticias/tag/$tag'
      preLoaderRoute: typeof NoticiasTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/categoria/$category': {
      id: '/noticias/categoria/$category'
      path: '/noticias/categoria/$category'
      fullPath: '/noticias/categoria/$category'
      preLoaderRoute: typeof NoticiasCategoriaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss': {
      id: '/api/public/rss'
      path: '/api/public/rss'
      fullPath: '/api/public/rss'
      preLoaderRoute: typeof ApiPublicRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noticias/nova': {
      id: '/admin/noticias/nova'
      path: '/nova'
      fullPath: '/admin/noticias/nova'
      preLoaderRoute: typeof AdminNoticiasNovaRouteImport
      parentRoute: typeof AdminNoticiasRoute
    }
    '/admin/noticias/$id': {
      id: '/admin/noticias/$id'
      path: '/$id'
      fullPath: '/admin/noticias/$id'
      preLoaderRoute: typeof AdminNoticiasIdRouteImport
      parentRoute: typeof AdminNoticiasRoute
    }
  }
}

interface AdminNoticiasRouteChildren {
  AdminNoticiasIdRoute: typeof AdminNoticiasIdRoute
  AdminNoticiasNovaRoute: typeof AdminNoticiasNovaRoute
}

const AdminNoticiasRouteChildren: AdminNoticiasRouteChildren = {
  AdminNoticiasIdRoute: AdminNoticiasIdRoute,
  AdminNoticiasNovaRoute: AdminNoticiasNovaRoute,
}

const AdminNoticiasRouteWithChildren = AdminNoticiasRoute._addFileChildren(
  AdminNoticiasRouteChildren,
)

interface AdminRouteChildren {
  AdminImportarRoute: typeof AdminImportarRoute
  AdminNoticiasRoute: typeof AdminNoticiasRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportarRoute: AdminImportarRoute,
  AdminNoticiasRoute: AdminNoticiasRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmpresaRouteChildren {
  EmpresaClientesRoute: typeof EmpresaClientesRoute
  EmpresaNossaHistoriaRoute: typeof EmpresaNossaHistoriaRoute
  EmpresaQuemSomosRoute: typeof EmpresaQuemSomosRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaClientesRoute: EmpresaClientesRoute,
  EmpresaNossaHistoriaRoute: EmpresaNossaHistoriaRoute,
  EmpresaQuemSomosRoute: EmpresaQuemSomosRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

interface SolucoesWebRouteChildren {
  SolucoesWebDesenvolvimentoDeSitesRoute: typeof SolucoesWebDesenvolvimentoDeSitesRoute
  SolucoesWebHospedagemRoute: typeof SolucoesWebHospedagemRoute
  SolucoesWebLandingPagesRoute: typeof SolucoesWebLandingPagesRoute
  SolucoesWebLojaVirtualRoute: typeof SolucoesWebLojaVirtualRoute
  SolucoesWebMarketingDigitalRoute: typeof SolucoesWebMarketingDigitalRoute
  SolucoesWebSeoGoogleRoute: typeof SolucoesWebSeoGoogleRoute
}

const SolucoesWebRouteChildren: SolucoesWebRouteChildren = {
  SolucoesWebDesenvolvimentoDeSitesRoute:
    SolucoesWebDesenvolvimentoDeSitesRoute,
  SolucoesWebHospedagemRoute: SolucoesWebHospedagemRoute,
  SolucoesWebLandingPagesRoute: SolucoesWebLandingPagesRoute,
  SolucoesWebLojaVirtualRoute: SolucoesWebLojaVirtualRoute,
  SolucoesWebMarketingDigitalRoute: SolucoesWebMarketingDigitalRoute,
  SolucoesWebSeoGoogleRoute: SolucoesWebSeoGoogleRoute,
}

const SolucoesWebRouteWithChildren = SolucoesWebRoute._addFileChildren(
  SolucoesWebRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClassificadosDeVeiculosRoute: ClassificadosDeVeiculosRoute,
  ContatoRoute: ContatoRoute,
  DicasParaECommerceRoute: DicasParaECommerceRoute,
  EmpresaRoute: EmpresaRouteWithChildren,
  ErrosNaCriacaoDeUmAplicativoRoute: ErrosNaCriacaoDeUmAplicativoRoute,
  InstagramParaEmpresasRoute: InstagramParaEmpresasRoute,
  NossosServicosRoute: NossosServicosRoute,
  NossosSistemasRoute: NossosSistemasRoute,
  OrcamentoRoute: OrcamentoRoute,
  PlataformaChinesaApostasCassinoRoute: PlataformaChinesaApostasCassinoRoute,
  ProgramaDeOrdemDeServicoRoute: ProgramaDeOrdemDeServicoRoute,
  SistemaDeCupomDescontosRoute: SistemaDeCupomDescontosRoute,
  SistemaDeLeilaoRoute: SistemaDeLeilaoRoute,
  SistemaDeLeilaoDeCentavosRoute: SistemaDeLeilaoDeCentavosRoute,
  SistemaDeLeilaoRuralRoute: SistemaDeLeilaoRuralRoute,
  SistemaDeOfertasCupomMarketplaceRoute: SistemaDeOfertasCupomMarketplaceRoute,
  SistemaDeRaspadinhaRoute: SistemaDeRaspadinhaRoute,
  SistemaDeRevendaDeVeiculosRoute: SistemaDeRevendaDeVeiculosRoute,
  SistemaDeRifasRoute: SistemaDeRifasRoute,
  SistemaSobDemandaNcBrasilRoute: SistemaSobDemandaNcBrasilRoute,
  SoftwareRoute: SoftwareRoute,
  SolucoesWebRoute: SolucoesWebRouteWithChildren,
  TrabalhosRealizadosRoute: TrabalhosRealizadosRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  PortfolioAplicativosCriadosRoute: PortfolioAplicativosCriadosRoute,
  PortfolioCriacaoDeAplicativosRoute: PortfolioCriacaoDeAplicativosRoute,
  PortfolioCriacaoDeLogomarcasRoute: PortfolioCriacaoDeLogomarcasRoute,
  PortfolioCriacaoDeSistemasRoute: PortfolioCriacaoDeSistemasRoute,
  PortfolioIdentidadeVisualRoute: PortfolioIdentidadeVisualRoute,
  PortfolioLogotiposCriadosRoute: PortfolioLogotiposCriadosRoute,
  PortfolioLojasVirtuaisCriadasRoute: PortfolioLojasVirtuaisCriadasRoute,
  PortfolioSistemaDeCompraColetivaRoute: PortfolioSistemaDeCompraColetivaRoute,
  PortfolioSistemasCriadosRoute: PortfolioSistemasCriadosRoute,
  PortfolioSitesCriadosRoute: PortfolioSitesCriadosRoute,
  ServicosAplicativosRoute: ServicosAplicativosRoute,
  ServicosConsultoriaRoute: ServicosConsultoriaRoute,
  ServicosDesenvolvimentoRoute: ServicosDesenvolvimentoRoute,
  ServicosFacebookAdsRoute: ServicosFacebookAdsRoute,
  ServicosGoogleAdsRoute: ServicosGoogleAdsRoute,
  ServicosIdentidadeVisualRoute: ServicosIdentidadeVisualRoute,
  ServicosSistemasWebRoute: ServicosSistemasWebRoute,
  SistemasSlugRoute: SistemasSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  SistemasIndexRoute: SistemasIndexRoute,
  ApiPublicRssRoute: ApiPublicRssRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
  NoticiasCategoriaCategoryRoute: NoticiasCategoriaCategoryRoute,
  NoticiasTagTagRoute: NoticiasTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
